// generate-readme.js
const fs = require('fs');
const path = require('path');

// Get all directories
const entries = fs.readdirSync('.', { withFileTypes: true });
const problemDirs = entries
  .filter(entry => entry.isDirectory() && /^\d+#_/.test(entry.name));

const formatName = (dirName) => {
  const [numberPart, ...rest] = dirName.split('#_');
  const number = parseInt(numberPart).toString(); // remove leading zeros
  const words = rest.join('_').split('_');
  const title = words.map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  return { number, title, dir: dirName };
};

const problems = problemDirs.map(d => formatName(d.name));

const readmeContent = `# 🧠 LeetCode Solutions in JavaScript

This repository contains my solutions and notes for LeetCode problems.  
Each problem has its own directory containing:

- \`description.txt\`
- \`notes.txt\`
- \`solution.js\`

---

## 📚 Problems List

${problems.map(p => `- [${p.number}. ${p.title}](${p.dir})`).join('\n')}

---

> Auto-generated by [generate-readme.js](./generate-readme.js)
`;

fs.writeFileSync('README.md', readmeContent);
console.log("✅ README.md generated.");

