
 name: Update README

 on:
   push:
     branches: [main]
   workflow_dispatch:

 jobs:
   generate-readme:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '18'


       - name: Run README generator
         run: node generate-readme.js

       - name: Commit and push changes
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git add README.md
           git commit -m "chore: auto-update README" || echo "No changes to commit"
           git push
